[book]
authors = ["Siriusmart"]
language = "en"
multilingual = false
src = "src"
title = "GM Tex API Docs"
description = "API documentation for GM Tex"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/gmornin/gmt-server/tree/master/docs/api"
edit-url-template = "https://github.com/gmornin/services/edit/master/docs/api/{path}"
